/**
 * Main thread entry to the isolated search worker. Keeps expensive indexing off UI.
 * No silent network model downloads: pass embeddings generated by a local model.
 */
export class EdgeSearchClient {
  constructor({url=new URL('./search-worker.js',import.meta.url),timeoutMs=60000}={}){
    if(typeof Worker!=='function')throw Error('Web Workers no disponibles');
    this.worker=new Worker(url,{type:'module'});this.pending=new Map();this.nextId=0;this.timeoutMs=timeoutMs;
    this.worker.onmessage=({data})=>{
      const job=this.pending.get(data.id);if(!job)return;
      this.pending.delete(data.id);clearTimeout(job.timer);
      if(data.error)job.reject(Error(data.error));else job.resolve(data.result);
    };
    this.worker.onerror=()=>{for(const job of this.pending.values()){clearTimeout(job.timer);job.reject(Error('Motor de búsqueda detenido'))}this.pending.clear()};
  }
  request(type,payload={}){
    const id=++this.nextId;
    return new Promise((resolve,reject)=>{
      const timer=setTimeout(()=>{this.pending.delete(id);reject(Error('Tiempo de búsqueda agotado'))},this.timeoutMs);
      this.pending.set(id,{resolve,reject,timer});this.worker.postMessage({id,type,...payload});
    });
  }
  build(rows,options={},name='default'){return this.request('BUILD',{rows,options,name})}
  query(query,options={},name='default'){return this.request('QUERY',{query,options,name})}
  stats(name='default'){return this.request('STATS',{name})}
  clear(name='default'){return this.request('CLEAR',{name})}
  close(){this.worker.terminate();for(const job of this.pending.values()){clearTimeout(job.timer);job.reject(Error('Motor cerrado'))}this.pending.clear()}
}
