"""Regenerate hashes whenever a shipped local engine asset changes."""
import pathlib, json, hashlib
root = pathlib.Path(__file__).resolve().parents[1]
files = []
for group in ['voice', 'vision']:
    for p in sorted((root/'offline/v1'/group).iterdir()):
        if p.name.endswith('LICENSE'): continue
        data = p.read_bytes()
        files.append({'group':group,'path':str(p.relative_to(root/'offline')),'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()})
p = root/'offline/audio-worklet.js'
files.append({'group':'voice','path':'audio-worklet.js','bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
payload = {'version':'expo-v1','files':files}
(root/'offline/assets.js').write_text('/* Generated by scripts/offline-manifest.py */\nglobalThis.NEXUS_OFFLINE_ASSETS='+json.dumps(payload,separators=(',',':'))+';\n')
print('Offline assets:',sum(f['bytes'] for f in files),'bytes')
